steps:

- id: docker-build
  name: gcr.io/cloud-builders/docker
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/eos-blocksigner:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/eos-blocksigner:latest',
    '-f', 'Dockerfile',
    '.'
  ]

images:
- gcr.io/$PROJECT_ID/eos-blocksigner:latest
- gcr.io/$PROJECT_ID/eos-blocksigner:$COMMIT_SHA
